name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test core
        uses: actions/setup-node@v1
        with:
          node-version: '17'
      - run: yarn install
      - run: yarn test:ci
